# Generated by Django 3.2.12 on 2022-03-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('team_name_red', models.CharField(default='team_1', max_length=20)),
                ('team_name_blue', models.CharField(default='team_2', max_length=20)),
                ('score_red', models.IntegerField()),
                ('score_blue', models.IntegerField()),
            ],
        ),
    ]
